In [114]:
import pandas as pd

In [186]:
#Pandas to be in float format.

In [116]:
pd.options.display.float_format = '{:,.2f}'.format

In [188]:
#Reading the File.

In [118]:
df = pd.read_csv("salaries_by_college_major.csv")

In [190]:
#We use the .head() method to peek at the top 5 rows of our dataframe.

In [120]:
df.head()

,Undergraduate Major,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 90th Percentile Salary,Group
0,Accounting,"46,000.00","77,100.00","42,200.00","152,000.00",Business
1,Aerospace Engineering,"57,700.00","101,000.00","64,300.00","161,000.00",STEM
2,Agriculture,"42,600.00","71,900.00","36,300.00","150,000.00",Business
3,Anthropology,"36,800.00","61,500.00","33,800.00","138,000.00",HASS
4,Architecture,"41,600.00","76,800.00","50,600.00","136,000.00",Business

In [ ]:
#To see the number of rows and columns, we can use the shape attribute.

In [122]:
df.shape

(51, 6)

In [ ]:
#We can access the column names directly with the columns attribute.

In [124]:
df.columns

Index(['Undergraduate Major', 'Starting Median Salary',
       'Mid-Career Median Salary', 'Mid-Career 10th Percentile Salary',
       'Mid-Career 90th Percentile Salary', 'Group'],
      dtype='object')

In [ ]:
#Use the .isna() method and see if there are any missing or junk data in our dataframe.

In [126]:
df.isna()

,Undergraduate Major,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 90th Percentile Salary,Group
0,False,False,False,False,False,False
1,False,False,False,False,False,False
2,False,False,False,False,False,False
3,False,False,False,False,False,False
4,False,False,False,False,False,False
5,False,False,False,False,False,False
6,False,False,False,False,False,False
7,False,False,False,False,False,False
8,False,False,False,False,False,False
9,False,False,False,False,False,False
10,False,False,False,False,False,False
11,False,False,False,False,False,False
12,False,False,False,False,False,False
13,False,False,False,False,False,False
14,False,False,False,False,False,False
15,False,False,False,False,False,False
16,False,False,False,False,False,False
17,False,False,False,False,False,False
18,False,False,False,False,False,False
19,False,False,False,False,False,False
20,False,False,False,False,False,False
21,False,False,False,False,False,False
22,False,False,False,False,False,False
23,False,False,False,False,False,False
24,False,False,False,False,False,False
25,False,False,False,False,False,False
26,False,False,False,False,False,False
27,False,False,False,False,False,False
28,False,False,False,False,False,False
29,False,False,False,False,False,False
30,False,False,False,False,False,False
31,False,False,False,False,False,False
32,False,False,False,False,False,False
33,False,False,False,False,False,False
34,False,False,False,False,False,False
35,False,False,False,False,False,False
36,False,False,False,False,False,False
37,False,False,False,False,False,False
38,False,False,False,False,False,False
39,False,False,False,False,False,False
40,False,False,False,False,False,False
41,False,False,False,False,False,False
42,False,False,False,False,False,False
43,False,False,False,False,False,False
44,False,False,False,False,False,False
45,False,False,False,False,False,False
46,False,False,False,False,False,False
47,False,False,False,False,False,False
48,False,False,False,False,False,False
49,False,False,False,False,False,False
50,False,True,True,True,True,True

In [192]:
#We use the .tail() method to peek at the last 5 rows of our dataframe.

In [128]:
df.tail()

,Undergraduate Major,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 90th Percentile Salary,Group
46,Psychology,"35,900.00","60,400.00","31,600.00","127,000.00",HASS
47,Religion,"34,100.00","52,000.00","29,700.00","96,400.00",HASS
48,Sociology,"36,500.00","58,200.00","30,700.00","118,000.00",HASS
49,Spanish,"34,000.00","53,100.00","31,000.00","96,400.00",HASS
50,Source: PayScale Inc.,NaN,NaN,NaN,NaN,NaN

In [194]:
#We use the .dropna() method from pandas to drop the row we don't want.

In [130]:
clean_df = df.dropna()

In [132]:
clean_df.tail()

,Undergraduate Major,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 90th Percentile Salary,Group
45,Political Science,"40,800.00","78,200.00","41,200.00","168,000.00",HASS
46,Psychology,"35,900.00","60,400.00","31,600.00","127,000.00",HASS
47,Religion,"34,100.00","52,000.00","29,700.00","96,400.00",HASS
48,Sociology,"36,500.00","58,200.00","30,700.00","118,000.00",HASS
49,Spanish,"34,000.00","53,100.00","31,000.00","96,400.00",HASS

In [196]:
#To access a particular column from a data frame, we can use the square bracket notation, like so.

In [134]:
clean_df["Starting Median Salary"]

0    46,000.00
1    57,700.00
2    42,600.00
3    36,800.00
4    41,600.00
5    35,800.00
6    38,800.00
7    43,000.00
8    63,200.00
9    42,600.00
10   53,900.00
11   38,100.00
12   61,400.00
13   55,900.00
14   53,700.00
15   35,000.00
16   35,900.00
17   50,100.00
18   34,900.00
19   60,900.00
20   38,000.00
21   37,900.00
22   47,900.00
23   39,100.00
24   41,200.00
25   43,500.00
26   35,700.00
27   38,800.00
28   39,200.00
29   37,800.00
30   57,700.00
31   49,100.00
32   36,100.00
33   40,900.00
34   35,600.00
35   49,200.00
36   40,800.00
37   45,400.00
38   57,900.00
39   35,900.00
40   54,200.00
41   39,900.00
42   39,900.00
43   74,300.00
44   50,300.00
45   40,800.00
46   35,900.00
47   34,100.00
48   36,500.00
49   34,000.00
Name: Starting Median Salary, dtype: float64

In [198]:
#To find the highest starting salary, we can simply chain the .max() method.

In [136]:
clean_df["Starting Median Salary"].max()

74300.0

In [ ]:
# The .idxmax() method will give us the index of the row with the largest value.

In [138]:
clean_df["Starting Median Salary"].idxmax()

43

In [ ]:
#To see the name of the major that corresponds to that particular row, we can use the .loc (location) property.

In [140]:
clean_df["Undergraduate Major"].loc[43]

'Physician Assistant'

In [204]:
#If you don't specify a particular column you can use the .loc property to retrieve an entire row.

In [142]:
clean_df.loc[43]

Undergraduate Major                  Physician Assistant
Starting Median Salary                         74,300.00
Mid-Career Median Salary                       91,700.00
Mid-Career 10th Percentile Salary              66,400.00
Mid-Career 90th Percentile Salary             124,000.00
Group                                               STEM
Name: 43, dtype: object

In [202]:
#What college major has the highest mid-career salary? How much do graduates with this major earn?
#(Mid-career is defined as having 10+ years of experience).

In [144]:
clean_df["Mid-Career Median Salary"].max()

107000.0

In [146]:
clean_df["Mid-Career Median Salary"].idxmax()

8

In [148]:
clean_df["Undergraduate Major"].loc[8]

'Chemical Engineering'

In [200]:
#Which college major has the lowest starting salary and how much do graduates earn after university?

In [150]:
clean_df["Starting Median Salary"].min()

34000.0

In [152]:
clean_df["Starting Median Salary"].idxmin()

49

In [154]:
clean_df["Undergraduate Major"].loc[49]

'Spanish'

In [206]:
#Which college major has the lowest mid-career salary and how much can people expect to earn with this degree?

In [156]:
clean_df["Mid-Career Median Salary"].min()

52000.0

In [158]:
clean_df["Mid-Career Median Salary"].idxmin()

18

In [160]:
clean_df["Undergraduate Major"].loc[18]

'Education'

In [212]:
#How would we calculate the difference between the earnings of the 10th and 90th percentile?
#Well, Pandas allows us to do simple arithmetic with entire columns, so all we need to do is use the .subtract()

In [162]:
clean_df['Mid-Career 90th Percentile Salary'].subtract(clean_df['Mid-Career 10th Percentile Salary'])

0    109,800.00
1     96,700.00
2    113,700.00
3    104,200.00
4     85,400.00
5     96,200.00
6     98,100.00
7    108,200.00
8    122,100.00
9    102,700.00
10    84,600.00
11   105,500.00
12    95,900.00
13    98,000.00
14   114,700.00
15    74,800.00
16   116,300.00
17   159,400.00
18    72,700.00
19    98,700.00
20    99,600.00
21   102,100.00
22   147,800.00
23    70,000.00
24    92,000.00
25   111,000.00
26    76,000.00
27    66,400.00
28   112,000.00
29    88,500.00
30   115,900.00
31    84,500.00
32    71,300.00
33   118,800.00
34   106,600.00
35   100,700.00
36   132,900.00
37   137,800.00
38    99,300.00
39   107,300.00
40    50,700.00
41    65,300.00
42   132,500.00
43    57,600.00
44   122,000.00
45   126,800.00
46    95,400.00
47    66,700.00
48    87,300.00
49    65,400.00
dtype: float64

In [ ]:
#The output of this computation will be another Pandas dataframe column. We can add this to our existing dataframe with the .insert() method.

In [164]:
spread_col = clean_df['Mid-Career 90th Percentile Salary'] - clean_df['Mid-Career 10th Percentile Salary']

In [166]:
clean_df.insert(1, 'Spread', spread_col)

In [168]:
clean_df.head()

,Undergraduate Major,Spread,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 90th Percentile Salary,Group
0,Accounting,"109,800.00","46,000.00","77,100.00","42,200.00","152,000.00",Business
1,Aerospace Engineering,"96,700.00","57,700.00","101,000.00","64,300.00","161,000.00",STEM
2,Agriculture,"113,700.00","42,600.00","71,900.00","36,300.00","150,000.00",Business
3,Anthropology,"104,200.00","36,800.00","61,500.00","33,800.00","138,000.00",HASS
4,Architecture,"85,400.00","41,600.00","76,800.00","50,600.00","136,000.00",Business

In [214]:
#To see which degrees have the smallest spread, we can use the .sort_values() method. 
#And since we are interested in only seeing the name of the degree and the major, we can pass a list of these two column names to look at the 
#.head() of these two columns exclusively.

In [170]:
low_risk = clean_df.sort_values('Spread')

In [172]:
low_risk[['Undergraduate Major', 'Spread']].head()

           Undergraduate Major    Spread
40                     Nursing 50,700.00
43         Physician Assistant 57,600.00
41                   Nutrition 65,300.00
49                     Spanish 65,400.00
27  Health Care Administration 66,400.00

In [216]:
#Using the .sort_values() method, can you find the degrees with the highest potential? 
#Find the top 5 degrees with the highest values in the 90th percentile.

In [174]:
highest_potential = clean_df.sort_values("Mid-Career 90th Percentile Salary", ascending=False)

In [176]:
highest_potential[["Undergraduate Major", "Mid-Career 90th Percentile Salary"]].head()

     Undergraduate Major  Mid-Career 90th Percentile Salary
17             Economics                         210,000.00
22               Finance                         195,000.00
8   Chemical Engineering                         194,000.00
37                  Math                         183,000.00
44               Physics                         178,000.00

In [218]:
#Also, find the degrees with the greatest spread in salaries. Which majors have the largest difference between high and low earners after graduation?

In [178]:
greatest_spread = clean_df.sort_values('Spread', ascending=False)

In [180]:
greatest_spread[["Undergraduate Major", "Spread"]].head()

   Undergraduate Major     Spread
17           Economics 159,400.00
22             Finance 147,800.00
37                Math 137,800.00
36           Marketing 132,900.00
42          Philosophy 132,500.00

In [222]:
# Oftentimes you will want to sum rows that belong to a particular category. For example, which category of degrees has the highest average salary? 
#Is it STEM, Business, or HASS (Humanities, Arts, and Social Science)? 

#To answer this question, we need to learn to use the .groupby() method. This allows us to manipulate data similar to a Microsoft Excel Pivot Table.
#We have three categories in the 'Group' column: STEM, HASS and Business. Let's count how many majors we have in each category.

In [182]:
clean_df.groupby('Group').count()

,Undergraduate Major,Spread,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 90th Percentile Salary
Group,,,,,,
Business,12,12,12,12,12,12
HASS,22,22,22,22,22,22
STEM,16,16,16,16,16,16

In [ ]:
#Now, can you use the .mean() method to find the average salary by group?

In [184]:
clean_df.groupby('Group').mean(numeric_only=True)

,Spread,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 90th Percentile Salary
Group,,,,,
Business,"103,958.33","44,633.33","75,083.33","43,566.67","147,525.00"
HASS,"95,218.18","37,186.36","62,968.18","34,145.45","129,363.64"
STEM,"101,600.00","53,862.50","90,812.50","56,025.00","157,625.00"

In [224]:
#Use .head(), .tail(), .shape and .columns to explore your DataFrame and find out the number of rows and columns as well as the column names.

#Look for NaN (not a number) values with .findna() and consider using .dropna() to clean up your DataFrame.

#You can access entire columns of a DataFrame using the square bracket notation: df['column name'] or df[['column name 1', 'column name 2', 'column name 3']]

#You can access individual cells in a DataFrame by chaining square brackets df['column name'][index] or using df['column name'].loc[index]

#The largest and smallest values, as well as their positions, can be found with methods like .max(), .min(), .idxmax() and .idxmin()

#You can sort the DataFrame with .sort_values() and add new columns with .insert()

#To create an Excel Style Pivot Table by grouping entries that belong to a particular category, use the .groupby() method